### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by GreYzZ** [ztizzlegaming/CSGOWinBig#101]
How can I add a admin and moderator tag for the chat.
like it's on csgowinbig.

**Comment by signedbydc** [comment]
Have you looked after it, before you make an "issues"? :)

**Comment by TheRod1990** [comment]
You can do it in the script.js on line 561. Just replace the profil string with yours ;)

**Comment by GreYzZ** [comment]
@TheRod1990 
thanks
