### ISSUE TITLE
Web-Antivirus "Pishing"

### ISSUE THREAD

**Issue by Braandn** [ztizzlegaming/CSGOWinBig#104]
If my friends (and me) try to connect to the site my webanti virus gives me this:

----------------------------------------------------------------------------------------------------------------------------------
Kaspersky
PURE 3.0
ACCESS DENIED
The access for the requested website is not allowed

URL-address:

{LINK REMOVED}

Has been blocked by Web Anti-Virus

Reason: Phishing address

Click here if you consider that the website has been mistakenly blocked.

Detection Method: Databases
Message posted on: 19:35:31

------------------------------------------------------------------------------------------------------------------------------

How can I fix this and why does it tells me that

**Comment by TheAnthonyNL** [comment]
What url lol...

**Comment by Braandn** [comment]
http://csgamble.tk

**Comment by andrewda** [comment]
Well, that's not the site's issue... I'm assuming it just blocks .tk domains (?) or that domain in particular is on some sort of blacklist...

**Comment by Braandn** [comment]
Hm okay, I will test it tomorrow !

**Comment by Braandn** [comment]
I checked it with an .de domain but I didnt work too^^...

**Comment by andrewda** [comment]
Again, I'm guessing the domain is on some kind of blacklist for whatever reason. Do some more testing and see if it's all CSGOWinBig-like sites or if it's just your sites.

**Comment by Braandn** [comment]
Lol .de is the German domain and my Web Anti-Virus is from a german company so I think not that ".de" is on a blocklist
