### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Xeroner** [ztizzlegaming/CSGOWinBig#105]
The will be winner animation ? @ztizzlegaming 
I found 2 files, meaby will help u

http://pastebin.com/pdfH4yaq
http://pastebin.com/TAtayr6z

**Comment by Xeroner** [comment]
Iv'e made it ! :))

**Comment by Braandn** [comment]
Can you post your code?

**Comment by Xeroner** [comment]
It's not ready yet for 100%.

**Comment by Xeroner** [comment]
BTW, meaby csgowinbig will have it

**Comment by GreYzZ** [comment]
@Xeroner 
maybe do a pull request

**Comment by Xeroner** [comment]
My script is completly different looking that csgowinbig so i can't just pull request. Look at csbox.pl

**Comment by GreYzZ** [comment]
@Xeroner 
Did you all changes by yourself?

**Comment by Xeroner** [comment]
@GreYzZ Yes i'm
