### ISSUE TITLE
i can't find database file !

### ISSUE THREAD

**Issue by NadirRed** [ztizzlegaming/CSGOWinBig#106]
Hi Guys,
please show me how to setup the database
because i don't find .sql file in the downloaded folder

thank you.

**Comment by Stuffa1991** [comment]
https://github.com/ztizzlegaming/CSGOWinBig/blob/master/database-config.sql

**Comment by Xeroner** [comment]
@NadirRed meaby close the issue?

**Comment by NadirRed** [comment]
thanks guys ^^
