### ISSUE TITLE
Integrate API

### ISSUE THREAD

**Issue by GreYzZ** [ztizzlegaming/CSGOWinBig#111]
Hey can someone help me to integrate the OPSkins.com API?
Or another good working API

**Comment by Xeroner** [comment]
There is some issue with some API configuration guide, don't be lazy just search .

**Comment by Stuffa1991** [comment]
https://github.com/ztizzlegaming/CSGOWinBig/issues/85

Im the one that created the tutorial, just ask if you got any questions

**Comment by Xeroner** [comment]
This is it ! :dancer:

**Comment by GreYzZ** [comment]
@Stuffa1991 
The GoogleAuthenticator.php is not longer available, can you post it again?
Or maybe you can create a new wiki page

**Comment by mx0c** [comment]
+1 Would be Great!
