### ISSUE TITLE
Bot taking wrong items

### ISSUE THREAD

**Issue by GreYzZ** [ztizzlegaming/CSGOWinBig#113]
Hello,
the bot is taking as commission the items which the winner placed.
It should be like he get the same items back and 
the bot takes the tax items from the winnings.

**Comment by Xeroner** [comment]
Do you have any programistic skills ?

**Comment by GreYzZ** [comment]
@Xeroner 
Not that huge?
Can you help?

**Comment by Xeroner** [comment]
Nope

**Comment by Xeroner** [comment]
BTW i think it's basic PHP skills ;))

**Comment by GreYzZ** [comment]
@Xeroner 
you fixed it at csbox.pl?

**Comment by Xeroner** [comment]
Nope, i don't want to.

**Comment by GreYzZ** [comment]
@Xeroner 
but it's possible?

**Comment by Xeroner** [comment]
My friend, everythink is possible :)))

**Comment by GreYzZ** [comment]
@Xeroner 
Oke with enaugh coding and programistic skill which I dont have :dancer:

**Comment by Xeroner** [comment]
Use google and go on :))
