### ISSUE TITLE
Chat doesn't save into SQL database

### ISSUE THREAD

**Issue by LilFuzzFuzz** [ztizzlegaming/CSGOWinBig#117]
For some reason, when you input a trade offer link or chat message, they do not get saved into SQL database.

I can grab information from the database but no save stuff. (I'm using a SQL database that came with the webhost, and I was able to create tables from PHP on another file!)

**Comment by mx0c** [comment]
what does /php/send-chat-message.php and /php/login-status.php return?

**Comment by LilFuzzFuzz** [comment]
{"success":1,"data":{"loginStatus":1,"userInfo":{"steamid":(steaminfohere) for login-status
and {"success":0,"errMsg":"The required text for the message was not sent correctly or was left blank. Please refresh and try again."} for send-chat-message.php
(That's what I see when I access the files)

**Comment by LilFuzzFuzz** [comment]
Update: Trade offers will get saved! But chat still isn't

**Comment by mx0c** [comment]
have the same problem im getting an 500 internal server error in the console.

**Comment by TheAnthonyNL** [comment]
Rename send-chat-message.php to populate-msg.php and do the same in script.js.

**Comment by LilFuzzFuzz** [comment]
Odd, didn't seem to work...
I can bare with no chat though.
