### ISSUE TITLE
server hosting web help?

### ISSUE THREAD

**Issue by eliasferreyra** [ztizzlegaming/CSGOWinBig#119]
window o linux?

**Comment by andrewda** [comment]
either

**Comment by baixinho154** [comment]
what are you looking for?

**Comment by eliasferreyra** [comment]
hosting web csgowinbig. select hosting window or linux?

**Comment by andrewda** [comment]
As I said, either one works. It just depends on which one you prefer or are most comfortable with.

**Comment by eliasferreyra** [comment]
thx my friend :D

**Comment by baixinho154** [comment]
Someone here asks me for help to set up my web and Steambot.

**Comment by andrewda** [comment]
What do you mean, @baixinho154? Are you trying to *get* help or *sell* help? If you're trying to get help, make a new issue. If you're trying to sell your help, this is not the place. Use https://reddit.com/r/SteamBotMarket

**Comment by TheAnthonyNL** [comment]
@andrewda with latest version of steambot its not allowed to sell it anymore... its the sticky on /r/SteamBot .

**Comment by TheAnthonyNL** [comment]
Oops meant https://github.com/Jessecar96/SteamBot/issues/847#issuecomment-159741215

**Comment by andrewda** [comment]
@TheAnthonyNL Indeed. I was just trying to give him a place to sell his help instead of spamming many different issue threads.
