### ISSUE TITLE
not save chat in mysql

### ISSUE THREAD

**Issue by eliasferreyra** [ztizzlegaming/CSGOWinBig#122]
500 (Internal Server Error).
HELP
http://subefotos.com/ver/?6cdd73587fa2519079464bbc19163c2fo.png

**Comment by KamyczeQ2** [comment]
https://github.com/ztizzlegaming/CSGOWinBig/issues/117

**Comment by KamyczeQ2** [comment]
have the same problem im getting an 500 internal server error in the console.

this not work https://github.com/ztizzlegaming/CSGOWinBig/issues/117

**Comment by eliasferreyra** [comment]
thx :D
