### ISSUE TITLE
Deposit Problems! need help!

### ISSUE THREAD

**Issue by Zouspants** [ztizzlegaming/CSGOWinBig#129]
Screenshot: http://prntscr.com/9ly6ff
my friend deposited a skin worth 0.4€ and the bot accepted the skin but the skin didnt came to the pot and i got that error on the screenshot. 

And when i tried to send the skin back it said confirm steamauth on your mobile phone but the auth is on the cmd how do i do??? i cant accept throw my phone please help!

**Comment by TheAnthonyNL** [comment]
Exec 0 confirm

**Comment by Zouspants** [comment]
didnt work can you please add me on steam? http://steamcommunity.com/id/CSGO-Rolling/

**Comment by Zouspants** [comment]
someone please help dont work

**Comment by Zouspants** [comment]
didnt work can you please add me on steam?
http://steamcommunity.com/id/CSGO-Rolling/
http://prntscr.com/9m3c7v

1. I cant send back his item it dont work with exec 0 confirm
2. If someone deposit over 0.20€ the bot accept it but it dont come in to
the pot error look like this: http://prntscr.com/9ly6ff
3. Where do i change Maxinum skins? now its 5 i want 10
Thanks for helping me :)

2016-01-04 16:16 GMT+01:00 TheAnthonyNL <notifications@github.com>:

**Comment by linkzy** [comment]
I removed this if statement from the bot:

if (IsAdmin)

And left only:

if (command.Equals("confirm"))
                {
                    Bot.AcceptAllMobileTradeConfirmations();
                    Log.Success("All trade offers confirmed... on bot: " + Bot.SteamUser.SteamID.ConvertToUInt64());
                }

Then my "exec 0 confirm" started working...

But i think its just because i didnt get how to set up the bot properly.

**Comment by Zouspants** [comment]
stupid question but where do i find if (isadmin)  ^^?

**Comment by Zouspants** [comment]
didnt work :/(

**Comment by GreYzZ** [comment]
@linkzy thanks for this simple fix
@TheAnthonyNL I can agree, that the command exec 0 confirm is only working if you delete this 
if (IsAdmin)

**Comment by TheAnthonyNL** [comment]
Well seems  your admins array im settings  is empty if that doesnt work

**Comment by scorpionofwar** [comment]
exec 0 confirm still does not confirm the trade
