### ISSUE TITLE
data base error

### ISSUE THREAD

**Issue by krozs** [ztizzlegaming/CSGOWinBig#13]
#1115 - Unknown character set: 'utf8mb4'

**Comment by RatexIndex** [comment]
I think the Problem is you upload the tables with uf8.

Example: Login phpmyadmin -> create a database -> than go to import -> and only upload the sql -> start upload

**Comment by krozs** [comment]
yap ty fixed

**Comment by RatexIndex** [comment]
Np Brah ;)
#CloseRequest ^^
