### ISSUE TITLE
Can´t change timer

### ISSUE THREAD

**Issue by JohnnySSS** [ztizzlegaming/CSGOWinBig#130]
I want to make pot 3600 seconds long. I changed in deposit.php this: 
$endTime = round(microtime(true) * 1000 + 3600000.0); 
But pot is anyways 120 seconds long, not 3600 even after setting it. Do I have to modify something else?

**Comment by linkzy** [comment]
You have to modify the bot:

if (timerTime >= 120)

change to:

if (timerTime >= 360)
