### ISSUE TITLE
make the background to black how?! 

### ISSUE THREAD

**Issue by Zouspants** [ztizzlegaming/CSGOWinBig#133]
Hello i wanna make my page all black background i dont want an image here is my damn code still not working: 

body {
	/* background-image: url(images/background.jpg); */ /* Background with 2 dudes */
	background-image: url(images/background.png); /* Blue digital camo background */
	background-color: black;
	background-repeat: no-repeat;
	/* background-position: center top; */
	height: 100%;
	width: 100%;
	font-family: Arial;
}

it is black ive tried to delete the background but it dont work... its just white please help me

**Comment by ztizzlegaming** [comment]
You're a mong, learn HTML and CSS before submitting an issue, good lord I swear people literally wnat everyone else to do everything for them, one little problem and they give up and want other people to do it for them.
