### ISSUE TITLE
affter depositing

### ISSUE THREAD

**Issue by eliasferreyra** [ztizzlegaming/CSGOWinBig#136]
affter depositing, steam bot consolo accepting offert, and nothing pass in web, inspect element and error:
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://steamcommunity.com') does not match the recipient window's origin ('http://www.facilpot.com').

 solution?

**Comment by Zouspants** [comment]
add me http://steamcommunity.com/id/aaaaaKung/ i maybe know :)

**Comment by Zouspants** [comment]
"BotWebsiteURL":"http://csgo-rolling.com", Be sure to have that correct in your bot file

**Comment by GreYzZ** [comment]
@eliasferreyra 
how did you do this with this "Add FACILPOT.COM to your STEAM nickname and get 5% bonus to your win amount!"?
Can you help with the code?

**Comment by eliasferreyra** [comment]
i dont work greyzz,, is decoration for now

**Comment by GreYzZ** [comment]
@eliasferreyra 
okay
BTW I like the design

**Comment by eliasferreyra** [comment]
help please, affter deposit, bot accepting trade, and error
http://subefotos.com/ver/?c1f49c7eee3ddd67ede07175cfb1fe9bo.png

**Comment by GreYzZ** [comment]
@eliasferreyra 
I had the same problem in the past, I re-compiled the bot and re-setup the whole 
site and it worked

**Comment by eliasferreyra** [comment]
"BotWebsiteURL":"http://facilpot.com",
"BotWebsiteName":"FACILPOT",
"BotDBPassword":"??", 
that I have to put password?? in setting.  bot

**Comment by GreYzZ** [comment]
@eliasferreyra 
Yes the password of your database so the bot can access to the database
and add the items deposited to "currentPot"
