### ISSUE TITLE
Error login

### ISSUE THREAD

**Issue by krozs** [ztizzlegaming/CSGOWinBig#14]
I put the site on vps. 

When i go to the site : http://prntscr.com/8gkquf
some info he got from db..... and other loading... 

When login : http://prntscr.com/8gkq72

I just edit the design !
soz my bad english ç.ç

**Comment by Visfan** [comment]
Error with a Login button somewhere. I had the same issue when installing. Not 100% sure, I'm drunk.

**Comment by RatexIndex** [comment]
I know the Problems you need to read the readme correct.
All is right and all works good i think you make the problem to your own ^^
I can help you add me on Skype RatexIndex and we can talk about this problem or i fix it over teamviewer. So but now i go sleep good night.

**Comment by krozs** [comment]
ok i will try fix

**Comment by krozs** [comment]
http://prntscr.com/8irkuf now i can login but , the pot and chat still loading...
http://prntscr.com/8irl76

any ideia ?

**Comment by krozs** [comment]
nvm its working.
