### ISSUE TITLE
Bot dont log in

### ISSUE THREAD

**Issue by Zouspants** [ztizzlegaming/CSGOWinBig#147]
Hello, my bot isnt working correcly!
ss: http://prntscr.com/9n6yyi
it just load like that does someone have a solution? 
it worked before then i tested my friends bot on my computer to see if it sent out the winning and it didint then couple of hours later the bot just didnt start someone know why?

**Comment by Zouspants** [comment]
please someone HELPP

**Comment by JohnnySSS** [comment]
That screenshot wont help much :/ You have to wait after the bot has loaded. Does it give a specific error or just that?

**Comment by Zouspants** [comment]
it just says that as far as i know... and it dont help with waiting ive waiting like 10 min + and still not loading something is wrong but idk what

**Comment by Zouspants** [comment]
if someone has teamviewer and maybe know why this issue happens please add me on steam here:http://steamcommunity.com/id/aaaaaKung/
