### ISSUE TITLE
Clicking 'about' causes the background image to shift 17px to the right

### ISSUE THREAD

**Issue by Scribbsc** [ztizzlegaming/CSGOWinBig#15]
This can be seen on the CSGOWinBig.com homepage.

Removing [Line 11 of style.css](https://github.com/RatexIndex/CSGOWinBig/blob/master/src/style.css#L11) seems to fix this, though further testing is needed to see if this causes any other issues.

First time doing anything on github, sorry if I screwed this up!

**Comment by ztizzlegaming** [comment]
Thanks, I will try this, and tell you if it works. I had noticed it shifting, but hadn't tried anything yet to fix it, so I appreciate you submitting this!

**Comment by ztizzlegaming** [comment]
It seems like that worked! I just committed it, thanks again!

**Comment by Scribbsc** [comment]
No worries. I figured since you're giving this away for free, I figured the least I could do is let you know :)
