### ISSUE TITLE
CSGOWinBig Discord?

### ISSUE THREAD

**Issue by andrewda** [ztizzlegaming/CSGOWinBig#150]
Seems like a Discord/Slack may be more effective for anyone who's having trouble setting up the script. We should make one for people who are new to CSGOWinBig and reserve the "Issues" section for *ACTUAL CODE ISSUES* and try to keep it from being used as a forum (spams everybody's inbox + hard to sort through actual issues in the code vs. "HOW DO I SETUP SCRIPT????")

**Comment by GreYzZ** [comment]
@andrewda 
maybe add some wiki pages how to simple set up the site and some possible fixes for the known issues

**Comment by Zouspants** [comment]
when i log in to my bot it just  say "lanch the bot" then write help for commands" then it dont log in someone have any ideas why this issue happen? it worked before until i changed to my friends bot

**Comment by TheAnthonyNL** [comment]
Following guides should be enough to set up everything...

**Comment by TheRod1990** [comment]
Thinking is good aswell

**Comment by Zouspants** [comment]
@TheAnthonyNL  Could you help me with my bot? 2 different people have tried to help me @GreYzZ  And @mx0c my bot wont start we do it correcly.. we have tested many different things but it dont work! please add me here; http://steamcommunity.com/id/aaaaaKung
