### ISSUE TITLE
How to limit socket accesses?

### ISSUE THREAD

**Issue by keinervonus** [ztizzlegaming/CSGOWinBig#162]
Hi.
Is there any way to limit the socket accesses. My hoster only allows 100/minute, 1000/hour and 5000/day wich results in this error:

Warning: get_headers() [function.get-headers]: Sorry, socket access was denied. The contingent for <b>this hour</b> has been exceeded, in /users/xxx/www/xxx/php/SteamAuthentication/steamauth/openid.php on line 315

How much accesses does the site need?

**Comment by andrewda** [comment]
By limiting "socket access", I believe you would be kicking users off the site, which is most likely not what you want. The best thing you could probably do is upgrade to a better host.

**Comment by keinervonus** [comment]
My hoster raises it if you ask them but i would like to know how much i would need first. Any suggestions?
