### ISSUE TITLE
Error 500 after steam login

### ISSUE THREAD

**Issue by Gicminos** [ztizzlegaming/CSGOWinBig#163]
Hello, the website respond me with Error 500 and blank page after the login.
I've checked the other issues and I can confirm that the url in index.html and settings.php is correct.
Site url: http://www.csgofish.me

**Comment by mx0c** [comment]
did you upload the database and the passwords.txt?

**Comment by Gicminos** [comment]
I've directly insert the password and api in the php file

**Comment by Gicminos** [comment]
Can anyone help me? D:

**Comment by andrewda** [comment]
Try reverting back to the CSGOWinBig code and use a passwords.txt file. I bet you inserted the passwords incorrectly.

**Comment by Gicminos** [comment]
Solved, i've missed the " ; " in a line :(
