### ISSUE TITLE
Chat doesn't save chat messages.

### ISSUE THREAD

**Issue by ICallHax** [ztizzlegaming/CSGOWinBig#167]
Hello,

So I recently completely reinstalled the script. And I had to input something into chat for the site to work as it says in the instructions. For some reason however, the chat doesn't seem to save the messages. You can still see the chat when you click enter and you can see your message. However, if you refresh the chat text is gone. What can I do to fix this?

Here is my site: www.csgofancy.com

Regards,
ICallHax

**Comment by MrBrist** [comment]
I have the same problem and i cannot figure out why its happening :/

**Comment by joshuabrand1** [comment]
You need to add a table to the database called 'chatBlacklist' with one field '	steamId64'

**Comment by ICallHax** [comment]
Ok, thanks @joshuabrand1 it fixed it.
