### ISSUE TITLE
loading..

### ISSUE THREAD

**Issue by emilkaaekudahl** [ztizzlegaming/CSGOWinBig#17]
all over my site it says "loading..."
http://skinflipper.com/csgowin/src/

**Comment by TheAnthonyNL** [comment]
Make sure your password.txt is being read and test your mysql connection.

so far i can see your password.txt file is not being read : http://skinflipper.com/csgowin/src/php/update.php

**Comment by emilkaaekudahl** [comment]
I hardcoded the pass into the default.php? For mysql

Sendt fra min iPhone

**Comment by emilkaaekudahl** [comment]
Fixed it now, it says "no file found" now tho.

**Comment by emilkaaekudahl** [comment]
Fatal error: Call to a member function fetchAll() on a non-object in C:\xampp\htdocs\csgowin\src\php\update.php on line 10

**Comment by emilkaaekudahl** [comment]
kay, fixed all except chat.

**Comment by TheAnthonyNL** [comment]
Find and add me on steam.

**Comment by emilkaaekudahl** [comment]
Im dxel, added you.

**Comment by emilkaaekudahl** [comment]
You are not replying on Steam, and I do still have problem. Signing in with steam doesnt sign me in.

**Comment by TheAnthonyNL** [comment]
Im on my way to work .... be patient lol.

**Comment by TheAnthonyNL** [comment]
i fixes all issues for him. This cam be closed.
