### ISSUE TITLE
Invalid SteamID32/64 saved in database when saving trade offer url

### ISSUE THREAD

**Issue by TheAnthonyNL** [ztizzlegaming/CSGOWinBig#18]
As posted earlier on another issue on how to fix i will post it here again:

Few people seems to have issues when it comes to saving their steam trade offer url. This occurs due the steamid32/64 being saved incorrectly in the database.

How to fix in 2 edits:

First edit:
From here: https://github.com/ztizzlegaming/CSGOWinBig/blob/master/src/php/save-trade-token.php#L37 

Line 37 till 43 replace them with the lines i posted below.
```php
# Get steam id
$steamUserId = $steamprofile['steamid'];
# Convert steam 64 id to steam 32 id
//Get the steamid (really the community id)
$communityid = $steamUserId;
//Get the map name
//See if the second number in the steamid (the auth server) is 0 or 1. Odd is 1, even is 0
$authserver = bcsub($communityid, '76561197960265728') & 1;
//Get the third number of the steamid
$authid = (bcsub($communityid, '76561197960265728')-$authserver)/2;
//Concatenate the STEAM_ prefix and the first number, which is always 0, as well as colons with the other two numbers
$steam32Id = "STEAM_0:$authserver:$authid";
```

Second edit:
https://github.com/ztizzlegaming/CSGOWinBig/blob/master/src/php/deposit.php#L19 & https://github.com/ztizzlegaming/CSGOWinBig/blob/master/src/php/check-items.php#L19 

Line 19 till 23 replace them with lines posted below.

```php
# Convert Steam ID to Steam64 ID
$idParts = explode(':', $tradeOwnerSteamId32);
$authServer = $idParts[1];
$accountNumber = $idParts[2];

function steamid32ToSteamid64($steamid32) {
    $iServer = "0";
    $iAuthID = "0";
     
    $szTmp = strtok($steamid32, ":");
     
    while(($szTmp = strtok(":")) !== false)
    {
        $szTmp2 = strtok(":");
        if($szTmp2 !== false)
        {
            $iServer = $szTmp;
            $iAuthID = $szTmp2;
        }
    }
    if($iAuthID == "0")
        return "0";
 
    $steamId64 = bcmul($iAuthID, "2");
    $steamId64 = bcadd($steamId64, bcadd("76561197960265728", $iServer)); 
	$part = explode('.',$steamId64);
	return $part[0];
}

//$tradeOwnerSteamId64 = ($accountNumber * 2) + ($authServer + 76561197960265728);
$tradeOwnerSteamId64 = steamid32ToSteamid64($tradeOwnerSteamId32);
```

**Comment by TheAnthonyNL** [comment]
https://github.com/ztizzlegaming/CSGOWinBig-SteamBot/issues/12#issuecomment-142183030 still testing this so far it keeps working so its good right?

**Comment by ztizzlegaming** [comment]
Hi, I appreciate the work you have put into this. If you want to use this instead of what I have done, by all means, go for it. However, for me at least, my code for calculating the steamID64 works, as I have shown out here: http://pastebin.com/MJcHAFw1. If your code doesn't work for calculating it and this does, by all means, use this method, but I am going to continue using what I have.

**Comment by TheAnthonyNL** [comment]
@ztizzlegaming  i know it works but for some reason it doesn't for other people.

So maybe it's nice to leave it as footnote ;).

**Comment by optiix** [comment]
Should 76561197960265728 be replaced with my bots 64ID?

**Comment by TheAnthonyNL** [comment]
@optiix no absolutely not. Its a number required for calculation. Do not mess with it.

**Comment by optiix** [comment]
@TheAnthonyNL 
Okey. Thanks!

**Comment by Laessen** [comment]
@TheAnthonyNL Is this fix still working?

**Comment by TheAnthonyNL** [comment]
Its implemented in latest version so yes.
