### ISSUE TITLE
Steam API error 500 and timer

### ISSUE THREAD

**Issue by IBeRamen** [ztizzlegaming/CSGOWinBig#181]
I tried everything and got no where. I am completely stumped when it comes to this.

Screenshot: http://i.imgur.com/kRER6Rx.png

Users can deposit items, the bot accepts it and adds it to the database. After accepting it and appearing on the website that error is spit out in console (Screenshot above). The items are still in the pot but the timer doesn't start even with 2+ players in. Once the pot reaches the max items (With the timer still not working). No winner is chosen, the bot keeps the items and crashes resetting the pot.

What could possibly be wrong?

Any advice helps.

**Comment by HansenDansen** [comment]
I got the same problem! Would be nice with some help here aswell! :)

**Comment by HansenDansen** [comment]
I can help you with it now! :) Add me and i'll help you :) https://steamcommunity.com/profiles/76561198068754660/

**Comment by IBeRamen** [comment]
For anyone wondering how to fix this go to your history row and add the following (You can replace the Steam ID with yours if you want - this will be replaced after the first pot):

https://imgur.com/dtbll6Y

(Set the date to yesterday)
