### ISSUE TITLE
Any recommendations for a chat bot for the website?

### ISSUE THREAD

**Issue by nickbijmoer** [ztizzlegaming/CSGOWinBig#187]
see title

**Comment by ICallHax** [comment]
What does a "chat bot" mean?

**Comment by nickbijmoer** [comment]
I would like to have a bot that runs on the website that can run commands or something like delete a message or mute a player, that kind of commands

**Comment by ICallHax** [comment]
Well I don't know what you mean by recommendations because you can't just
find a bot like that, so you have to code it yourself manually.

**Comment by nickbijmoer** [comment]
Okey thanks
