### ISSUE TITLE
Pot animation issue

### ISSUE THREAD

**Issue by nickbijmoer** [ztizzlegaming/CSGOWinBig#199]
Hello, I have been following the pot animation tutorial on the wiki page, but now after the pot has ended, the animation appear and then dissapear in a millisecond. Any toughts how i could fix this?

**Comment by TarantelTM** [comment]
On following the Tutorial all will work

**Comment by nickbijmoer** [comment]
I did... :(

**Comment by nickbijmoer** [comment]
Okey I fixed it, I had 2 jquery scripts in my header
