### ISSUE TITLE
loading… (Already tried the password)

### ISSUE THREAD

**Issue by aselhd** [ztizzlegaming/CSGOWinBig#20]
I downloaded your script last night and need some help. I haven't actually bought the host yet so I have been testing with wampserver. Basically, I can get everything but the php scripts to work. I think it has to do with some confusion while I am setting up the mysql server. Here are some screenshots of where I am at.
https://gyazo.com/82ce8ccfd63995c483816c5767fdbb8e
https://gyazo.com/39ba63d0dfd7b373ba764f284e0a5dbe
https://gyazo.com/460fb2bae73fe433e87d6ded4c5199ce
https://gyazo.com/3a7edf4294c764bd0e24b7ececdc9395
https://gyazo.com/a1e8c84cc804d47ef043f8781f4159bd
https://gyazo.com/ddd61120a6696423b2358635acd86fa7
https://gyazo.com/d997247e86fa9dde9c363206bb0b175c
I am not sure if I miss-typed something or what but I can't seem to find my mistake. Thanks so much.

**Comment by aselhd** [comment]
I think I may have found the source of the problem. When I go to my website (csgoruns) www.csgoruns.com/php/steam-login-handle.php it says "no file found." Everything is in my webroot. I am not sure why the site can't detect the files in the php folder. Please help.
https://gyazo.com/670206487c0429fccbfe9974b7b84270
https://gyazo.com/871dd61993f90f87e949b77f67e02130
https://gyazo.com/eab16746007c052aee4ab4b2b35722b4

**Comment by TheAnthonyNL** [comment]
Fixed it for him this can be closed.

**Comment by ImEmil** [comment]
Anthon maybe share the fix so others doesn't have to spam with new issues? 

Thanks

**Comment by TheAnthonyNL** [comment]
Well like everyone else make sure the path to the password.txt is correct...
