### ISSUE TITLE
Chat messages don't stay

### ISSUE THREAD

**Issue by Ryan1154** [ztizzlegaming/CSGOWinBig#217]
Chat messages don't stay. When i input a message through any account it post it to the chat but dosen't update the Database and reloading the page it doesn't stick.

**Comment by loke0046** [comment]
have you fixed it ?? beacuse i have the same problem

**Comment by Ryan1154** [comment]
No sorry, I've decided to scrap this and went with another source since it's bot isn't capable anymore.
