### ISSUE TITLE
Chat working, Pot loading, history loading

### ISSUE THREAD

**Issue by ArthurBugan** [ztizzlegaming/CSGOWinBig#235]
I downloaded the project, changed everything as instructed, my login works but the pot doesnt show up.

Here is a screenshot: http://prntscr.com/eywg5u

**Comment by LucasFormiga** [comment]
Same here.

**Comment by ArthurBugan** [comment]
@LucasFormiga Did u find solution for some problem? I also changed the URL on the script.js for my bot trade URL but It keep sending trade request to the CS GO Win Big BOT, Did you have this error too?

**Comment by zouspants123321** [comment]
u need to change it in the bot too and the index
