### ISSUE TITLE
The bot doesn't respond to offers

### ISSUE THREAD

**Issue by crankpower** [ztizzlegaming/CSGOWinBig#24]
I wanted to change the bot little bit so when someone deposit items they convert into credits.
Thats the changed deposit.php: http://pastebin.com/LhgmjvXb
The changed depositTradeOfferUserHandler: http://pastebin.com/8L3APrCt
I am not sure why its not responding but can I get some help please?

**Comment by TheAnthonyNL** [comment]
Does it see trade offers at all or not?

**Comment by crankpower** [comment]
Well in the log file says: INFO: TradeOffer notification

**Comment by TheAnthonyNL** [comment]
add me on steam...

**Comment by crankpower** [comment]
The problem is fixed, my settings file's botcontrolclass was the wrong one for some reason, thanks again.

**Comment by iLogix** [comment]
you can close the issue to get the issue list clean. :)
