### ISSUE TITLE
Can´t login through Steam

### ISSUE THREAD

**Issue by signedbydc** [ztizzlegaming/CSGOWinBig#30]
Hello

I´m learning by doing, and this is an awesome project to work with - Thanks.

But I´m have some problems with the steam login.
After I try to login, it return me to "steam-login-handle.php" with the message "User is not logged in."

I have done all the Readme steps and the password, API key seems to work

Anyone had the same problem?
I really hope there is a kind person there will help me out..

DC

**Comment by signedbydc** [comment]
I find the problem by myself.

Its was the login link.

**Comment by dannarn23** [comment]
What was the problem? It would be nice if you shared with us what's causing the error :/ I got it too..
