### ISSUE TITLE
My site is stuck on loading....

### ISSUE THREAD

**Issue by J0nafin** [ztizzlegaming/CSGOWinBig#38]
Hey guys,
I've tried the trouble shooting method multiple times and i still can't get it to work. 

http://www.csgovegas.com/

https://gyazo.com/01e3647ec4da1074dafc4f9d4e0d4350
^issue im getting

https://gyazo.com/30deaf70a13e06a7ab9e05eb93eb48af
^is this in the correct place for the passwords.txt?

https://gyazo.com/54c0ccd2d2b6186a79485e0f66147290
^here is my public_html

https://gyazo.com/58843444e1c1dfe1f1ba70fdbadd6cc4
^is this correct?

Thanks!

**Comment by andrewda** [comment]
In your `settings.php` file write

    $fileLoc = $_SERVER['DOCUMENT_ROOT'] . '/../passwords.txt';

instead of

    $fileLoc = $_SERVER['DOCUMENT_ROOT'] . 'home/jtseng526/passwords.txt

**Comment by J0nafin** [comment]
I changed the settings.php per your instructions but nothing has changed.
