### ISSUE TITLE
How to change pot total and change cut %

### ISSUE THREAD

**Issue by J0nafin** [ztizzlegaming/CSGOWinBig#42]
Hi, the site is up and running. I would like to know how to change the pot total to be less than 60. Also change the cut % from 2% to 3 or 4%. Thanks!

**Comment by RatexIndex** [comment]
https://github.com/ztizzlegaming/CSGOWinBig/blob/master/src/php/deposit.php#L163
https://github.com/ztizzlegaming/CSGOWinBig/blob/master/src/php/deposit.php#L169

**Comment by J0nafin** [comment]
Thank you so much!

**Comment by Keyjk** [comment]
This have to get changed :)

**Comment by andrewda** [comment]
https://github.com/ztizzlegaming/CSGOWinBig/blob/master/src/php/deposit.php#L200
https://github.com/ztizzlegaming/CSGOWinBig/blob/master/src/php/deposit.php#L206

**Comment by ztizzlegaming** [comment]
Oh I just realized you don't actually need the $maxPotCount variable in check-items.php, I'll remove that

**Comment by TheRod1990** [comment]
is the $userPrice value in percent? so change to 0.05 for example?

**Comment by andrewda** [comment]
@TheRod1990 No, `$userPrice` should not be changed as it is simply the amount that the winner won. If you're looking to change the cut, take a look at #95 to help understand.

**Comment by TheRod1990** [comment]
@andrewda Got that. Thanks!
