### ISSUE TITLE
passwords.txt database password

### ISSUE THREAD

**Issue by CSGOHeist** [ztizzlegaming/CSGOWinBig#49]
Hi,

I am trying to setup the site on my GoDaddy web hosting account. ( csgoheist.com ) The package includes web hosting and MySQL databases. However I have followed your steps but am stuck on what to put for the database password. I have googles everywhere for how to find the database details on godaddy but they are all out dated. This is the page i see, next to the very badly drawn red star is the database i have setup, and uploaded the database .sql file you gave onto. 
![image](https://cloud.githubusercontent.com/assets/15159790/10545184/50a623e8-741f-11e5-915d-62046878a971.png)  I cannot work out how to find the database's password? Unless it is the password to the user account that has admin rights to the database? Can anyone help?

Thanks.

**Comment by RatexIndex** [comment]
Is that your first page or why do you cant read the readme ?
All what you need is understand !!! Sorry but you have issues like a ninja

**Comment by CSGOHeist** [comment]
You mean where it says '{"default-password":"YOUR DATABASE PASSWORD","steamAPIKey":"YOUR STEAM API KEY"}'

I cant find out the the database password is.
I am asking if it is the password to the admin account of the database or if the actual database has a password.

**Comment by RatexIndex** [comment]
that i mean with kind provider its not the best option to set up a gmabling page

**Comment by CSGOHeist** [comment]
What do you recommend then?

**Comment by CSGOHeist** [comment]
Do I just need to buy another sql server? Or do I need to buy another web hosting package again?
