### ISSUE TITLE
Can't get the chat to work

### ISSUE THREAD

**Issue by Dreburwar** [ztizzlegaming/CSGOWinBig#5]
The messages get saved in the database, but the messages don't show on the website

**Comment by ztizzlegaming** [comment]
I'm gonna need more info than that bud, are you getting any javascript errors?

**Comment by Dreburwar** [comment]
I'm only seeing this error: PHP Fatal error:  Call to undefined function getsteamapikey() in /php/update.php on line 42

**Comment by ztizzlegaming** [comment]
Well it looks like the capitalization of it is off. Make sure that the capitalization of the function call in update.php is the same as the function declaration in default.php

**Comment by Dreburwar** [comment]
Fixed the problem Thx but a new one occured xd
