### ISSUE TITLE
Depositing not working 

### ISSUE THREAD

**Issue by Abdokhaled** [ztizzlegaming/CSGOWinBig#54]
I have configured the not and deposited and accepted the trade and it appear in the site 0/60 items deposited

**Comment by TheAnthonyNL** [comment]
First does your bot see the trade offers? If not, are you sure you have setup the correct api key (the api key from the bot itself).

**Comment by Abdokhaled** [comment]
do I have to setup the C# CSGO steambot I only did the website on a host

**Comment by Keyjk** [comment]
Jeah you have. You have to setup the settings.json in Bot/Bin/Debug (AND Release)

**Comment by Abdokhaled** [comment]
Should I setup it with the website on same vps ?

**Comment by andrewda** [comment]
It doesn't have to be on the same VPS, it just has to connect to your MySQL server.

**Comment by demoxz** [comment]
You mean you have to download this: https://github.com/ztizzlegaming/CSGOWinBig-SteamBot ?
Only this code https://github.com/ztizzlegaming/CSGOWinBig is not enough?

**Comment by andrewda** [comment]
@demoxz You have to download ztizzlegaming/CSGOWinBig-SteamBot to run the bot. ztizzlegaming/CSGOWinBig is just for the website.

**Comment by demoxz** [comment]
@andrewda I have already figured it out, but thank you anyway.
