### ISSUE TITLE
Getting error when I try to login through steam?

### ISSUE THREAD

**Issue by lowheartrate** [ztizzlegaming/CSGOWinBig#56]
When I go to login to steam for my website it doesn't let me and it just echos "ERROR" on the steam login page and won't let me login to my website and doesn't redirect me to my website either because of the fact that it failed to log me in. Anyone help me fix this please!? SS: http://i.imgur.com/TLsb007.png

**UPDATE:** I changed it so my it isn't in its own seperate directory and in my main page now but still getting a different error. For some reason when I login through steam it redirects me to a blank page and echos *User is not logged in.* and I looked into the file where that error is located (*steamauth.php*) but cannot seem to find the issue?

**Comment by alanfort** [comment]
Did you edit the index.html ? and add your website for reddirect?

**Comment by lowheartrate** [comment]
I ended up fixing it myself overnight, thank you :)

**Comment by nexativez** [comment]
Hello
I have the same problem but my site url is complete addet to all .html and steamauth settings.
What can i do ? 
Thanks for any help
