### ISSUE TITLE
"User is not logged in." Login error

### ISSUE THREAD

**Issue by dannarn23** [ztizzlegaming/CSGOWinBig#58]
When I am going to log in on my website I get the Steam Community login and when I login with Steam I get an error message saying "User is not logged in."

Please help me! :/ I have tried everything and don't know whats wrong.. :/

**Comment by demoxz** [comment]
Try to change everything to http://YOURLINK.com in these files:

Lines 44 and 92 of index.html, line 96 of support.html, line 82 of donations.html, and line 148 of prices.html. Here, you must modify the sign in url to have your own website's url. You must change where it says 'openid.return_to=' and 'openid.realm=' to be your own website's url.

**Comment by dannarn23** [comment]
I have... :s But I will check all the files if there is something wrong :)

**Comment by dannarn23** [comment]
I've looked through all the files and nothing is wrong! What could be the fault then?

**Comment by demoxz** [comment]
Did you wrote it correct? For example: index.html line 44:
"https://steamcommunity.com/openid/login?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=checkid_setup&openid.return_to=http%3A%2F%2Fputyourlinkinhere.com%2Fphp%2Fsteam-login-handle.php&openid.realm=http%3A%2F%2Fputyourlinkinhere.com&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select">

Where you find "putyourlinkinhere.com" change to your site link. Don't write www. Http is wrote already before it. Deleting www helped me to fix this error.

**Comment by dannarn23** [comment]
I will try to remove www. :) I will update you as soon I edit my files

**Comment by dannarn23** [comment]
It works! :+1: Thx demoxz for your help! :+1: to you!!
