### ISSUE TITLE
Timer Issue Fix

### ISSUE THREAD

**Issue by Stuffa1991** [ztizzlegaming/CSGOWinBig#60]
I identified the error, seems like you have to have a history to make the timer start, it doesnt make the history row as it should in the database, thats the error :) made one manually and the timer started right away on first deposit :)

``` php
# Check if this is the first, second, or another deposit
$stmt = $db->query('SELECT * FROM history ORDER BY id DESC');
$mostRecentHistory = $stmt->fetch();

# If items is not empty, then this is the first deposit
$mostRecentItems = $mostRecentHistory['allItemsJson'];
if (strlen($mostRecentItems) > 0) {
    # Put a new row in, starting the next pot/round. However, don't start the timer yet.
    $stmt = $db->query('INSERT INTO history (endTime) VALUES (0)');
    $startTimer = 0;
}

# If there is already a round going but the timer hasn't started yet, then check to see if there are multiple people in the round
if ($mostRecentHistory['endTime'] === '0') {
    if (strlen($mostRecentItems) === 0) {
        $stmt = $db->query('SELECT * FROM currentPot');
        $allItemsCurPot = $stmt->fetchAll();
        $steamId = $allItemsCurPot[0]['ownerSteamId64'];

        $startTimer = 0;

        foreach ($allItemsCurPot as $item) {
            if ($steamId !== $item['ownerSteamId64']) {
                # There are multiple people in the pot, start the timer
                $endTime = round(microtime(true) * 1000 + 120000.0);
                $stmt = $db->prepare('UPDATE history SET endTime = :endtime');
                $stmt->bindValue(':endtime', $endTime);
                $stmt->execute();

                $startTimer = 1;
            }
        }
    }
} else { # This is if the timer is already running. It doesn't matter what $startTimer is
    $startTimer = 0;
}
```

So the code for depositing is expecting a row with endTime 0 in the Database, and it made it work to manually make a row with the following SQL

``` php
INSERT INTO history (endTime) VALUES (0)
```

What i did in steps is
1. Execute the sql
2. Deposit an item and let the timer run out
3. Succes??

It seems like this is the same as with the chat, where it expects the site to have a history like the chat expects a message to already be there

**Comment by TheAnthonyNL** [comment]
Well for me it did put a new history line tho but it didn't start the timer...

**Comment by TheAnthonyNL** [comment]
This is totally not needed ... you only need 2 different people to enter else it wont work.

**Comment by lowheartrate** [comment]
@TheAnthonyNL Actually without following this step my website wouldn't start the timer when two people enter. After adding values to the *history* table as this step states it all worked flawlessly.

**Comment by Stuffa1991** [comment]
@TheAnthonyNL The point isnt that YOUR site wont work unless 2 enters, the point is that the first time you "install" the website and database, just like the chat not working without manually entering a message in the database, the timer/pot system wont start or work before you put in a manual row with the SQL i provided and is provided in deposit.php

**Comment by TheAnthonyNL** [comment]
Hmm i see well i will fix this for you guys if someone can help me with it

**Comment by Stuffa1991** [comment]
@TheAnthonyNL This is a fix for first time installs of the site :) and the website is supposed only to start the timer when 2 different steamId's enter :)

**Comment by TheAnthonyNL** [comment]
I know

**Comment by mantazzo** [comment]
I can confirm adding the first line myself to history fixed the same issue for me. Two different players - timer doesn't start; added line and made additional few items deposit - timer is now fully working.

**Comment by TheAnthonyNL** [comment]
@Stuffa1991  i only meant to update the deposit.php  so that you don't have to manual add the sql after you installed the site ¬¬/ but nobody cares so i won't update it.

**Comment by hach3** [comment]
Thx guys ! i luv you :p
