### ISSUE TITLE
How to change minimum deposit, round timer, pot item max, and % cut?

### ISSUE THREAD

**Issue by Laessen** [ztizzlegaming/CSGOWinBig#64]
Title says all, I would like to start this issue so that it is easy to reference all the major configuration needs for the beginner.

**Comment by J0nafin** [comment]
Please check closed issues before posting new ones. https://github.com/ztizzlegaming/CSGOWinBig/issues/42

**Comment by TheAnthonyNL** [comment]
@Laessen please check the open/ closed issues. This is asked before.

**Comment by Laessen** [comment]
I have already seen that closed issue. @TheAnthonyNL @J0nafin

It doesn't address minimum deposit or round timer. Also, I feel like this should have been included in the readme because all this stuff is pretty necessary.

**Comment by TheAnthonyNL** [comment]
Check-items.php : @bottom => $minDeposit = $totalPrice >= 100 ? 1 : 0;

Where 100 = $1, 10 = $0.1, 1 = $0.01

Round timer is on deposit.php => $endTime = round(microtime(true) * 1000 + 120000.0);
