### ISSUE TITLE
Nvm.

### ISSUE THREAD

**Issue by TheAnthonyNL** [ztizzlegaming/CSGOWinBig#65]
Empty

**Comment by michel1056** [comment]
This guy is awesome he fixt my problems and is still helping me when I have a issue/

**Comment by demoxz** [comment]
I don't want to create a new issue, I just want to ask: Is this jackpot provably fair?

**Comment by optiix** [comment]
TheAnthonyDL helped me yesterday. Very friendly!

**Comment by TheAnthonyNL** [comment]
Pleasw add your timezone in the profile comment or here i catch people on bsd times :(.
