### ISSUE TITLE
Timer ends and no trade

### ISSUE THREAD

**Issue by Laessen** [ztizzlegaming/CSGOWinBig#68]
Here's my problem: The bot accepts everything perfectly now, it goes into the pot, items and prices appear on webpage, timer starts ticking (fixed the stuck timer, added the sql code), it ticks to zero and then goes blank (the time disappears and it goes blank), and then obviously the winner trade is never sent.

So as far as I can see, the bot didn't even get the command to trade back, which means the error must be in the php. I honestly don't know how to check the php logs, if anyone can help that would be great.

But in the meantime, anyone have this issue? Any fixes?

**Comment by Laessen** [comment]
Also, how do i clear the items already in the pot so it can restart? Just manually in phpmyadmin?

**Comment by Laessen** [comment]
Ok, so apparently you need to put in the max number of skins before it goes. So fixed-ish even though that defeats the purpose of a timer... whatever it works.

**Comment by Laessen** [comment]
A new problem though: trade offer was not sent to the winner.

[CSGO TEST BOT 2015-11-13 21:33:55] INFO: TradeOffer notification
[CSGO TEST BOT 2015-11-13 21:33:56] SUCCESS: Offer approved, accepting.
[CSGO TEST BOT 2015-11-13 21:33:58] SUCCESS: Response received from check-items.php: 
{"success":1,"data":{"totalPrice":800,"minDeposit":1,"allItems":"[{\"classId\":\"1035124635\",\"instanceId\":\"302028390\",\"marketName\":\"AWP | Sun in Leo (Factory New)\",\"rarityName\":\"Industrial Grade\",\"rarityColor\":\"5e98d9\",\"price\":800,\"iconUrl\":\"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot621FA957OnHdTRD746JmImMn-O6ZezVlz4CvJYj2LqXpNmj0Vaw8kVvZG_7LNSScgJsZF_S-VO7w-e51Ij84srJoVgQJg\"}]"}}
[CSGO TEST BOT 2015-11-13 21:34:01] SUCCESS: Offer accepted from STEAM_0:1:118783342
[CSGO TEST BOT 2015-11-13 21:34:01] SUCCESS: [{"classId":"1035124635","instanceId":"302028390","marketName":"AWP | Sun in Leo (Factory New)","rarityName":"Industrial Grade","rarityColor":"5e98d9","price":800,"iconUrl":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot621FA957OnHdTRD746JmImMn-O6ZezVlz4CvJYj2LqXpNmj0Vaw8kVvZG_7LNSScgJsZF_S-VO7w-e51Ij84srJoVgQJg"}]
[CSGO TEST BOT 2015-11-13 21:34:06] SUCCESS: Response received from deposit.php: {"success":1,"data":{"minDeposit":1,"potOver":1,"winnerSteamId":"STEAM_0:1:118783342","winnerTradeToken":"0NuxH4EW","tradeItems":[{"id":"4","0":"4","classId":"360463485","1":"360463485","instanceId":"480085569","2":"480085569","ownerSteamId64":"76561198115359713","3":"76561198115359713","ownerSteamId32":"STEAM_0:1:77546992","4":"STEAM_0:1:77546992","itemName":"USP-S | Guardian (Factory New)","5":"USP-S | Guardian (Factory New)","itemPrice":"81","6":"81","itemRarityName":"Restricted","7":"Restricted","itemRarityColor":"8847ff","8":"8847ff","itemIcon":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpoo6m1FBRp3_bGcjhQ09-jq5WYh8jxP77Wl2VF18l4jeHVu9Wh3gzlqRU6NmqhINXDelA9MliBr1O_kLjuh5Dt7sjLnyBlviJ0syvD30vgdbWoQSw","9":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpoo6m1FBRp3_bGcjhQ09-jq5WYh8jxP77Wl2VF18l4jeHVu9Wh3gzlqRU6NmqhINXDelA9MliBr1O_kLjuh5Dt7sjLnyBlviJ0syvD30vgdbWoQSw"},{"id":"1","0":"1","classId":"519990188","1":"519990188","instanceId":"302028390","2":"302028390","ownerSteamId64":"76561198197832413","3":"76561198197832413","ownerSteamId32":"STEAM_0:1:118783342","4":"STEAM_0:1:118783342","itemName":"UMP-45 | Indigo (Factory New)","5":"UMP-45 | Indigo (Factory New)","itemPrice":"100","6":"100","itemRarityName":"Consumer Grade","7":"Consumer Grade","itemRarityColor":"b0c3d9","8":"b0c3d9","itemIcon":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpoo7e1f1JfwPz3eDNG5du5q4GFk8jzIb7IqWdY781lxL7Aodqt3Vfn-Ec-NWjzJ9CXd1RvYFDW_wXtwermh5W9uc-fySEyv3M8pSGKN-yLqT0","9":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpoo7e1f1JfwPz3eDNG5du5q4GFk8jzIb7IqWdY781lxL7Aodqt3Vfn-Ec-NWjzJ9CXd1RvYFDW_wXtwermh5W9uc-fySEyv3M8pSGKN-yLqT0"},{"id":"2","0":"2","classId":"310864852","1":"310864852","instanceId":"188530170","2":"188530170","ownerSteamId64":"76561198197832413","3":"76561198197832413","ownerSteamId32":"STEAM_0:1:118783342","4":"STEAM_0:1:118783342","itemName":"StatTrak\u2122 FAMAS | Doomkitty (Field-Tested)","5":"StatTrak\u2122 FAMAS | Doomkitty (Field-Tested)","itemPrice":"100","6":"100","itemRarityName":"Mil-Spec Grade","7":"Mil-Spec Grade","itemRarityColor":"4b69ff","8":"4b69ff","itemIcon":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposLuoKhRf2-r3dTJN4de_gJSSqPrxN7LEmyUEv5Yii7uUpN32ilWw_kVqYzyhcYPAcgY5Y1GGqwS_xe7s0Ze1tJrB1zI97efXhTnO","9":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposLuoKhRf2-r3dTJN4de_gJSSqPrxN7LEmyUEv5Yii7uUpN32ilWw_kVqYzyhcYPAcgY5Y1GGqwS_xe7s0Ze1tJrB1zI97efXhTnO"},{"id":"3","0":"3","classId":"520029476","1":"520029476","instanceId":"188530139","2":"188530139","ownerSteamId64":"76561198115359713","3":"76561198115359713","ownerSteamId32":"STEAM_0:1:77546992","4":"STEAM_0:1:77546992","itemName":"Five-SeveN | Fowl Play (Well-Worn)","5":"Five-SeveN | Fowl Play (Well-Worn)","itemPrice":"200","6":"200","itemRarityName":"Classified","7":"Classified","itemRarityColor":"d32ce6","8":"d32ce6","itemIcon":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposLOzLhRlxfbGTjxT04nhq4aOluP8NqnCqWZU7Mxkh6fD9tytiwCw_hJlN2zycIORIQVoYAyB-we9yO7uhsXpvsidz3BjuCBx-z-DyFBP_k7D","9":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposLOzLhRlxfbGTjxT04nhq4aOluP8NqnCqWZU7Mxkh6fD9tytiwCw_hJlN2zycIORIQVoYAyB-we9yO7uhsXpvsidz3BjuCBx-z-DyFBP_k7D"},{"id":"5","0":"5","classId":"1233402153","1":"1233402153","instanceId":"302028390","2":"302028390","ownerSteamId64":"76561198115359713","3":"76561198115359713","ownerSteamId32":"STEAM_0:1:77546992","4":"STEAM_0:1:77546992","itemName":"Desert Eagle | Midnight Storm (Minimal Wear)","5":"Desert Eagle | Midnight Storm (Minimal Wear)","itemPrice":"200","6":"200","itemRarityName":"Industrial Grade","7":"Industrial Grade","itemRarityColor":"5e98d9","8":"5e98d9","itemIcon":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposr-kLAtl7PLFTi5H7c-im5KGqPv9NLPF2GpU7pcgj-_E9oj02wPm-EQ4YW2ncdTAcVA6YVGG_lO3xOq71MLo6MnXiSw0xSmk0RY","9":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposr-kLAtl7PLFTi5H7c-im5KGqPv9NLPF2GpU7pcgj-_E9oj02wPm-EQ4YW2ncdTAcVA6YVGG_lO3xOq71MLo6MnXiSw0xSmk0RY"},{"id":"6","0":"6","classId":"1035124635","1":"1035124635","instanceId":"302028390","2":"302028390","ownerSteamId64":"76561198197832413","3":"76561198197832413","ownerSteamId32":"STEAM_0:1:118783342","4":"STEAM_0:1:118783342","itemName":"AWP | Sun in Leo (Factory New)","5":"AWP | Sun in Leo (Factory New)","itemPrice":"800","6":"800","itemRarityName":"Industrial Grade","7":"Industrial Grade","itemRarityColor":"5e98d9","8":"5e98d9","itemIcon":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot621FA957OnHdTRD746JmImMn-O6ZezVlz4CvJYj2LqXpNmj0Vaw8kVvZG_7LNSScgJsZF_S-VO7w-e51Ij84srJoVgQJg","9":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot621FA957OnHdTRD746JmImMn-O6ZezVlz4CvJYj2LqXpNmj0Vaw8kVvZG_7LNSScgJsZF_S-VO7w-e51Ij84srJoVgQJg"}],"profitItems":[]}}
[CSGO TEST BOT 2015-11-13 21:34:06] ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at SteamBot.DepositTradeOfferUserHandler.OnNewTradeOffer(TradeOffer offer) in C:\Users\KingLaessen\Desktop\CSGOWinBig-SteamBot-master\SteamBot\DepositTradeOfferUserHandler.cs:line 212
   at SteamBot.Bot.TradeOfferRouter(TradeOffer offer) in C:\Users\KingLaessen\Desktop\CSGOWinBig-SteamBot-master\SteamBot\Bot.cs:line 844
   at SteamTrade.TradeOffer.TradeOfferManager.GetTradeOffersSince(Int32 unixTimeStamp) in C:\Users\KingLaessen\Desktop\CSGOWinBig-SteamBot-master\SteamTrade\TradeOffer\TradeOfferManager.cs:line 87
   at SteamTrade.TradeOffer.TradeOfferManager.GetOffers() in C:\Users\KingLaessen\Desktop\CSGOWinBig-SteamBot-master\SteamTrade\TradeOffer\TradeOfferManager.cs:line 111
   at SteamBot.Bot.<HandleSteamMessage>b__73_13(NotificationCallback callback) in C:\Users\KingLaessen\Desktop\CSGOWinBig-SteamBot-master\SteamBot\Bot.cs:line 684
   at SteamKit2.CallbackMsgExtensions.Handle[T](ICallbackMsg msg, Action`1 handler)
   at SteamBot.Bot.HandleSteamMessage(ICallbackMsg msg) in C:\Users\KingLaessen\Desktop\CSGOWinBig-SteamBot-master\SteamBot\Bot.cs:line 672
   at SteamBot.Bot.BackgroundWorkerOnDoWork(Object sender, DoWorkEventArgs doWorkEventArgs) in C:\Users\KingLaessen\Desktop\CSGOWinBig-SteamBot-master\SteamBot\Bot.cs:line 941
[CSGO TEST BOT 2015-11-13 21:34:06] WARN: Restarting bot...

**Comment by Laessen** [comment]
The last part after "object reference not set to an instance of an object" is what most concerns me.

**Comment by Stuffa1991** [comment]
From what im aware of and from what i've experienced the timer should work as intended and not as you are saying
The purpose of the timer is to end rounds after the timer is ended.

But try giving this a go
https://github.com/ztizzlegaming/CSGOWinBig/issues/65

At school right now else i would love to help :)

**Comment by Laessen** [comment]
@Stuffa1991 When the timer ticks down to zero nothing happens, the trade only starts to go through the bot after the pot fills up. 

Just FYI, this has way too many issues, I have moved on to another bot and website.

**Comment by TheAnthonyNL** [comment]
@laessen add me on steam please.
