### ISSUE TITLE
No winner is being picked

### ISSUE THREAD

**Issue by Dreburwar** [ztizzlegaming/CSGOWinBig#7]
There are no js errors.. Nothing happens

**Comment by M60Warrior** [comment]
Are you sure you have put enough items to trigger the winner selection?

It is defaulted at 100 so you would need to deposit 100 items.
You can change that amount in /php/deposit.php on line 7.

**Comment by Dreburwar** [comment]
Yeah it is.

**Comment by M60Warrior** [comment]
Are there entries in the currentpot table in the database?

**Comment by Dreburwar** [comment]
Yea

**Comment by M60Warrior** [comment]
Did you manually deposit all the skins or did you deposit a few then duplicate them in the DB?

**Comment by Dreburwar** [comment]
Duplicated

**Comment by M60Warrior** [comment]
Could you add me on steam so we can talk easier? http://steamcommunity.com/id/910374/

**Comment by ztizzlegaming** [comment]
Yea you have to actually deposit the last skin, because the winner is picked in deposit.php when the item is deposited.

**Comment by Dreburwar** [comment]
Ahh, Alright
