### ISSUE TITLE
Steam Bot Error 

### ISSUE THREAD

**Issue by ICallHax** [ztizzlegaming/CSGOWinBig#73]
Hi,

So I have been trying really hard to get my website running. Today I encountered the following error

https://gyazo.com/3e2f603863d23aecbf6a71490cea93c6

My Log: http://pastebin.com/NG6M1Rt2

My settings: http://pastebin.com/ApFmS83W (I have the correct API I just wrote it out for security reasons)

I don't know what I am doing wrong. Please Help :D

If you want to contact me here is the bot acount I am using http://steamcommunity.com/profiles/76561198216547607/

**Comment by andrewda** [comment]
This should go in https://github.com/ztizzlegaming/CSGOWinBig-SteamBot

**Comment by keinervonus** [comment]
@ICallHax Did you solve the issue?

**Comment by ICallHax** [comment]
@keinervonus Sorry, I forgot about this thread. Closed. I fixed it by reinstalling the site.
