### ISSUE TITLE
Compile bot

### ISSUE THREAD

**Issue by GreYzZ** [ztizzlegaming/CSGOWinBig#78]
Do I need to have a older version of Visual Studio?
I'm currently have Visual Studio 15.
And I cant open the file and compile

**Comment by chiiledgamer1985** [comment]
to build the bot use Visual Studio 2012

**Comment by RatexIndex** [comment]
With Visual Studio 2015 it works to all what you need to do is open the sln file

**Comment by chiiledgamer1985** [comment]
same as 2012 tho ratexlndex

**Comment by RatexIndex** [comment]
all works good i think you need to upgrade the NET Framework Stats to use Visual Studio

**Comment by andrewda** [comment]
For future reference, anything relating to the CSGOWinBig bot should go in the bot repo, https://github.com/ztizzlegaming/CSGOWinBig-SteamBot.
