### ISSUE TITLE
Bot Error

### ISSUE THREAD

**Issue by M60Warrior** [ztizzlegaming/CSGOWinBig#8]
When the winner is selected I keep getting this error:

![image](https://cloud.githubusercontent.com/assets/3887281/9290883/509ad27e-4358-11e5-82b8-632a8655f2fa.png)

**Comment by ztizzlegaming** [comment]
Okay, so this might just be an issue with Steam. Sometimes the Steam API messes up and you just have to wait for a little bit for it to fix itself. If waiting a little while, maybe 30 minutes to an hour, doesn't fix it, I would uncomment [this line](https://github.com/ztizzlegaming/CSGOWinBig-SteamBot/blob/master/SteamBot/DepositTradeOfferUserHandler.cs#L213) and make sure that eacn item's asset ID is actually in the bot's inventory, which you can see by going to this url: http://steamcommunity.com/profiles/[BOT 64BIT ID]/inventory/json/730/2, adding your bot's 64bit ID. Also, make sure that you put your own bot's id [here](https://github.com/ztizzlegaming/CSGOWinBig-SteamBot/blob/master/SteamBot/DepositTradeOfferUserHandler.cs#L176). Try all that and see if any of it works, and if it doesn't we'll try something else!

**Comment by M60Warrior** [comment]
Yeah, About 30ish minutes after I posted this it started working.
