### ISSUE TITLE
Multiple deposits

### ISSUE THREAD

**Issue by GreYzZ** [ztizzlegaming/CSGOWinBig#82]
Users can do multiple deposits.
That mean 2times 10 items

**Comment by TheAnthonyNL** [comment]
Yea this is not a issue lol.

**Comment by GreYzZ** [comment]
@TheAnthonyNL  is it possible to stop this?

**Comment by TheAnthonyNL** [comment]
Implement a feature to count items deposit from currentPot and if it exceeds 10 decline all trades from that user ... but this is useless anyway (in my opinion).
