### ISSUE TITLE
Mysql item base

### ISSUE THREAD

**Issue by Xeroner** [ztizzlegaming/CSGOWinBig#85]
Hello, can anybody update item database ? Becouse it's realy realy old and have a lot of 0 prices.
@ztizzlegaming

**Comment by Stuffa1991** [comment]
If you delete the 0 prices, it uses the prices directly from the market :)

**Comment by Xeroner** [comment]
And then for time to time steam blocking connection :)

**Comment by Stuffa1991** [comment]
Worked on a method getting prices via www.bitskins.com api, both csgojackpot and csgowild uses it

And it managed to work it out last night, i can tell what to do tomorrow :)

**Comment by Xeroner** [comment]
Fully free and unlimited?

**Comment by Stuffa1991** [comment]
Its free and you can do 8 requests a second :)

**Comment by Xeroner** [comment]
8 is to small i think for bigger jackpot

**Comment by Stuffa1991** [comment]
You can contact them to gain more, but i think that cost extra :) ill release a detailed guide or just the files if people wants it, going to bed soon :)

**Comment by GreYzZ** [comment]
@Stuffa1991 
can you share the implemention of the API with us?

**Comment by Stuffa1991** [comment]
Okay i'll make this as detailed as i can :)

I tried making the code i made so versatile so you only have to change the URL in check-items.php

Step by Step
1. Create an Account on BitSkins.com
2. Create Two-Factor Authentication - https://bitskins.com/settings
In this step its important you write down the "secret" code right under the QR code
Write it down or remember it, it will be needed later
3. Create API access
Write down your api-key it will be needed later

Thats it for BitSkins.com, you can close it now :)

Now to the important parts

1.
Create a file called GoogleAuthenticator.php
Paste this in http://codeshare.io/ROdWA

2.
Create a file called price.php
Paste this in http://codeshare.io/fRELz

3. Upload this to a folder on your website.

4. Change $secret in price.php to the secret from under the QR from bitskins

5. The same with $api, change that to the api-key provided by bitskins

6. In php/check-items.php change the URL of $marketObj from 
´´´php
$marketObj = json_decode(file_get_contents("http://steamcommunity.com/market/priceoverview/?currency=1&appid=730&market_hash_name=$hash"), true);
´´´
to
´´´php
$marketObj = json_decode(file_get_contents("http://yourwebsite.com/php/price.php$hash"), true);
´´´

And thats about it, your bot should now retrieve bitskins prices, which are used by csgowild and csgojackpot :)

**Comment by rfalkner** [comment]
I followed your guide 100% @Stuffa1991 - how can i check if my prices update? And when will they update?

Best regards

**Comment by Xeroner** [comment]
@rfalkner you need to replace steamcommunity lines to this script. This will not update your database man. It's should check price when user joining the pot.

**Comment by Stuffa1991** [comment]
@rfalkner, to keep the prices you have to add something in the check-items.php

Like so on line 136~

```PHP
if (isset($medianPrice)) {
			$price = doubleval(substr($medianPrice, 1)) * 100;
			$sql = "INSERT INTO items (marketName, avgPrice30Days) 
					VALUES (:marketName, :avgPrice30Days)
					ON DUPLICATE KEY UPDATE avgPrice30Days = :newPrice";
			$stmt = $db->prepare($sql);
			$stmt->bindValue(':marketName', $marketName);
			$stmt->bindValue(':avgPrice30Days', $price);
			$stmt->bindValue(':newPrice', $price);
            $stmt->execute();
		} else {
			$price = doubleval(substr($lowestPrice, 1)) * 100;
			$sql = "INSERT INTO items (marketName, avgPrice30Days) 
					VALUES (:marketName, :avgPrice30Days)
					ON DUPLICATE KEY UPDATE avgPrice30Days = :newPrice";
			$stmt = $db->prepare($sql);
			$stmt->bindValue(':marketName', $marketName);
			$stmt->bindValue(':avgPrice30Days', $price);
			$stmt->bindValue(':newPrice', $price);
            $stmt->execute();
		}
```

**Comment by Xeroner** [comment]
@Stuffa1991 script need to check first ,, if item exist do not insert but update ,,

**Comment by Stuffa1991** [comment]
Well the update part isnt actually supposed to be there, cause it will never occure, cause the script itself finds if the values exist and if it does it returns the price, therefore an update will never occure and is just there for no reason :D

**Comment by Xeroner** [comment]
But if table is empty? :dancer:

**Comment by Stuffa1991** [comment]
It will update the price only if the price is set to 0, else it will insert

As you can see ON DUPLICATE KEY UPDATE, means that if the thing it tries to insert is already there just update it instead, so its a sort of a fail safe for if the items that exist has a value of 0 :)

**Comment by Xeroner** [comment]
@Stuffa1991 you're right :)

**Comment by GreYzZ** [comment]
@Stuffa1991 
The GoogleAuthenticator.php is not longer available, can you post it again?

**Comment by mx0c** [comment]
+1 Would be great!
