### ISSUE TITLE
Get username insted of "Logout" 

### ISSUE THREAD

**Issue by rfalkner** [ztizzlegaming/CSGOWinBig#89]
Is this possible? If yes, is there a simple solution?

Best regards

**Comment by Stuffa1991** [comment]
If you rename index.html to index.php

and add in the top of the file
´´´PHP
<?php
include ('php/SteamAuthentication/steamauth/steamauth.php');  
include ('php/SteamAuthentication/steamauth/userInfo.php');
?>
´´´

Then you can do 

´´´PHP
<?php
echo "Welcome " . $steamprofile['personaname'] .' ';
?>
´´´

**Comment by rfalkner** [comment]
Sweet ma man.

**Comment by TheAnthonyNL** [comment]
Can be done way much easier without changing to index.php will post tomorrow

**Comment by rfalkner** [comment]
I did it with php allready. 

That way i can include files also, so i dont have to change content 5 places ;-)
