### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bagda391** [ztizzlegaming/CSGOWinBig#9]
I'm getting "No OpenID Server found at http://steamcommunity.com/openid/id/(steam64id here)". Any solution? I e-mailed you.

**Comment by bagda391** [comment]
I did some research and this is what I found: https://github.com/SmItH197/SteamAuthentication/issues/54

I'm currently hosting on 000webhost.com

**Comment by ztizzlegaming** [comment]
I talked to baga391 outside of Github, and the problem was 000webhost.

**Comment by ADAMPOKE111** [comment]
In what way was the problem 000webhost?
