### ISSUE TITLE
Changing fee on site

### ISSUE THREAD

**Issue by rfalkner** [ztizzlegaming/CSGOWinBig#91]
I would like to change the fee from 2% to 10% on my site.

How do i do this?

I believe its somewhere in this code:

foreach ($allItems as $item) {
		if ($give) {
			array_push($itemsToGive, $item);
			continue;
		}

		$itemPrice = intval($item['itemPrice']);
		$itemPercentage = $itemPrice / $totalPotPrice;

		if ($keepPercentage + $itemPercentage > 0.05) {
			array_push($itemsToGive, $item);
			$give = true;
			continue;
		}

		if ($keepPercentage + $itemPercentage >= 0.02 && $keepPercentage < 0.02) {
			array_push($itemsToKeep, $item);
			$give = true;
			continue;
		}

		array_push($itemsToKeep, $item);
		$keepPercentage += $itemPercentage;
	}

**Comment by Xeroner** [comment]
if ($keepPercentage + $itemPercentage > 0.05) {
        array_push($itemsToGive, $item);
        $give = true;
        continue;
    }

    if ($keepPercentage + $itemPercentage >= 0.02 && $keepPercentage < 0.02) {
        array_push($itemsToKeep, $item);
        $give = true;
        continue;
    }

**Comment by Xeroner** [comment]
change 0.02 to yours and 0.05 to yours
