### ISSUE TITLE
Backgroud Problem 

### ISSUE THREAD

**Issue by GreYzZ** [ztizzlegaming/CSGOWinBig#93]
I have this problem that the background is not moving with the site.
So if some more items are in the pot the site is getting black 
and you can't see the background anymore.
http://prntscr.com/9aa981

Maybe you have a fix for this?

**Comment by TheAnthonyNL** [comment]
Use

**Comment by TheAnthonyNL** [comment]
background-color: black;
	background-repeat: no-repeat;
	/* background-position: center top; */  
    background-attachment: fixed;

Use that as css your site will scroll over the background ;)

**Comment by andrewda** [comment]
You might also want to use

```css
background-color: black;
background-repeat: no-repeat;
-webkit-background-size: cover;
-moz-background-size: cover;
-o-background-size: cover;
background-size: cover;

background-attachment: fixed;
```

to force the background to fit the screen.

**Comment by GreYzZ** [comment]
@TheAnthonyNL @andrewda 
Thanks
