### ISSUE TITLE
LOADING STUCK FOR EVER!

### ISSUE THREAD

**Issue by JapanseMixxx** [ztizzlegaming/CSGOWinBig#94]
Hello guys i have inserted everything correct if i go to: /php/login-status.php it is empty..

What should i do!

**Comment by TheAnthonyNL** [comment]
Will help tomorrow. As you contacted me already.

**Comment by JapanseMixxx** [comment]
jaa ik praat nederlands hahaha ik heb je al bericht gestuurd ik begrijp er niks van ik heb alles precies overgenomen en eerst kreeg ik zon melding: no file found dat is nu gefixed ik moest passwords.txt goed neer zetten maar nog steeds loading thanks dat je wilt helpen;)

**Comment by xMGxMods** [comment]
Ye I need help with this too :/
