### ISSUE TITLE
Steam cannot send trade offer to someone who isn't your friend.

### ISSUE THREAD

**Issue by ICallHax** [ztizzlegaming/CSGOWinBig#96]
Title says it all. When someone who hasn't added my bot tries to send a trade offer via the deposit button it tells him he cant send the trade offer as he hasn't added the bot. I know what the problem is. It is that when I click the deposit button it uses this trade offer link. https://steamcommunity.com/tradeoffer/new/?partner=256281879 

This doesn't work if you are not friends with the bot.

However this link does 
https://steamcommunity.com/tradeoffer/new/?partner=256281879&token=NkvrhKfc 

and so my question is how do I change the deposit button to use this trade link. Thanks

**Comment by wwcam** [comment]
You change the a href urls...

**Comment by TheAnthonyNL** [comment]
Copy pasted from the readme : Line 149 of script.js. Here, you must put in the trade url of your own bot.

**Comment by ICallHax** [comment]
Ya I was stupid. I recently changed hosts so when I was changing the script.js files trade link it was updating my old website hosted on the previous host and I was viewing the new site with no changes if that makes sense. Fixed
