### ISSUE TITLE
Maintenance page

### ISSUE THREAD

**Issue by GreYzZ** [ztizzlegaming/CSGOWinBig#97]
Hey guys,
I saw that there is a maintenance site.
https://github.com/ztizzlegaming/CSGOWinBig/blob/master/src/index.html#L73
How can I activate this page?
So if someone want to join the site he only see this text

**Comment by andrewda** [comment]
That is simply text shown on the main page to indicate that the site is under maintenance. To "activate" it, remove the `<!--` and `-->`, making the line only `<h1>NOTE: The site is undergoing maintenance. Please bear with us.</h1>`. This will have absolutely no affect on the rest of the site, though, so even if you do display this message, it's possible for the site to be working fine.

**Comment by GreYzZ** [comment]
@andrewda 
Okay thanks
