### ISSUE TITLE
I CANT RECEIVE ANY CHATMESSAGES FROM OTHER PLAYERS

### ISSUE THREAD

**Issue by JapanseMixxx** [ztizzlegaming/CSGOWinBig#99]
I can't receive any message but what i type is in the database...?
http://www.csgowinfast.com

is my url

**Comment by TheAnthonyNL** [comment]
Seems i can write and see ..

**Comment by JapanseMixxx** [comment]
yes but you have to refresh the page bij F5 and normally it goes automaticly
